# This application is not clusterable, so keep replicaCount to 1
replicaCount: 1

image:
  repository: fardin01/fardin-payment-provider
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}

service:
  type: ClusterIP
  port: 80

resources:
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 50m
     memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}
